### ISSUE TITLE
Buffer is not defined

### ISSUE THREAD

**Issue by gilamran** [christsim/multicoin-address-validator#54]
When working with [esbuild](https://github.com/evanw/esbuild)/[vite](https://vitejs.dev/) we are not bundling node modules by default. This cause this library to crash with this error:
```
Uncaught ReferenceError: Buffer is not defined
    at node_modules/multicoin-address-validator/src/crypto/blake256.js (blake256.js:32)
    at __require (multicoin-address-validator.js?v=6adeb2e6:12)
    at node_modules/multicoin-address-validator/src/crypto/utils.js (utils.js:3)
    at __require (multicoin-address-validator.js?v=6adeb2e6:12)
    at node_modules/multicoin-address-validator/src/ripple_validator.js (ripple_validator.js:1)
    at __require (multicoin-address-validator.js?v=6adeb2e6:12)
    at node_modules/multicoin-address-validator/src/currencies.js (currencies.js:1)
    at __require (multicoin-address-validator.js?v=6adeb2e6:12)
    at node_modules/multicoin-address-validator/src/wallet_address_validator.js (wallet_address_validator.js:1)
    at __require (multicoin-address-validator.js?v=6adeb2e6:12)
```
Maybe the best thing to do is to import a `Buffer` library to be able to run on the browser without relaying on the bundlers (Like webpack)

Here's an easy way to see it in action: [here](https://stackblitz.com/edit/vite-yqzz6u)
Thanks

**Comment by gilamran** [comment]
https://github.com/evanw/esbuild/issues/1626

**Comment by emrecantra** [comment]
I also get this error with reactjs

**Comment by christsim** [comment]
Still happening?  what version of node are you using?  Seems ok in my react project.

**Comment by CherryDT** [comment]
Same error here, with SvelteKit

node 16

**Comment by p-nadeem** [comment]
is there any solution for this

**Comment by chamith-onramper** [comment]
Is there any solution for this issue ?

**Comment by sali-s** [comment]
It happened when I update my NodeJS to v18.0 , and updating ReactScripts from v4 to v5

Does anyone find a solution?

**Comment by sali-s** [comment]
I found the solution here:
https://github.com/christsim/multicoin-address-validator/issues/74#issuecomment-1212334884

**Comment by christsim** [comment]
fixed in 0.5.16

**Comment by jack40tall** [comment]
I'm still getting this error when running in ReactJS in the browser as of 3/13/2024.
